import Link from 'next/link';

export const metadata = {
  title: 'Terms of Service — N.E.X.A Loop',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-2xl mx-auto px-6 py-16">
        <Link
          href="/"
          className="text-sm text-indigo-600 hover:text-indigo-700 font-medium mb-8 inline-block"
        >
          &larr; Back to N.E.X.A Loop
        </Link>

        <h1 className="text-3xl font-bold text-slate-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-slate-400 mb-10">Last updated: May 2026</p>

        <div className="prose prose-slate prose-sm max-w-none space-y-6">
          <section>
            <h2 className="text-lg font-semibold text-slate-900 mb-3">1. Acceptance of Terms</h2>
            <p className="text-slate-600 leading-relaxed">
              By accessing or using N.E.X.A Loop (&quot;the Service&quot;), you agree to be bound by
              these Terms of Service. If you are using the Service on behalf of an organisation, you
              represent that you have authority to bind that organisation to these terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-900 mb-3">2. Description of Service</h2>
            <p className="text-slate-600 leading-relaxed">
              N.E.X.A Loop is a supply chain compliance and traceability platform designed for
              EU-facing fashion brands. The Service enables organisations to manage supplier data,
              track compliance documents, and generate regulatory outputs including ESPR Digital
              Product Passports and EPR exports.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-900 mb-3">3. User Accounts</h2>
            <p className="text-slate-600 leading-relaxed">
              You are responsible for maintaining the confidentiality of your account credentials
              and for all activities that occur under your account. You agree to notify us
              immediately of any unauthorised use of your account.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-900 mb-3">4. Data and Privacy</h2>
            <p className="text-slate-600 leading-relaxed">
              Your use of the Service is also governed by our{' '}
              <Link href="/privacy" className="text-indigo-600 hover:text-indigo-700 underline">
                Privacy Policy
              </Link>
              . We process data in accordance with GDPR and applicable EU data protection
              regulations. All data is hosted within the European Union.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-900 mb-3">5. Limitation of Liability</h2>
            <p className="text-slate-600 leading-relaxed">
              The Service is provided &quot;as is&quot; without warranties of any kind. N.E.X.A Loop
              shall not be liable for any indirect, incidental, or consequential damages arising
              from your use of the Service. Regulatory outputs generated by the Service are
              informational and do not constitute legal advice.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-900 mb-3">6. Contact</h2>
            <p className="text-slate-600 leading-relaxed">
              For questions about these terms, contact us at{' '}
              <span className="text-slate-900 font-medium">legal@nexaloop.eu</span>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
